U4X-618: UI for Sync task types
METS-Programme/esm-ugandaemr-exchange pull request #34
Opened 2024-07-16 21:10 UTC by Daphne210

2024-07-22 14:05 UTC, jabahum requested changes
fix conflicts

2024-07-23 05:33 UTC, Daphne210 commented
> fix conflicts

This has been resolved

2024-08-05 13:08 UTC, jabahum commented on src/root.component.tsx
> +          <Route path="/schedule-manager" element={<ScheduleManager />} />
looks like u just removed your route to sync-task-types yet you needed to add it below schedule-manager

2024-08-06 05:52 UTC, akileng56 approved these changes

2024-08-06 06:35 UTC, jabahum approved these changes

2024-08-06 06:35 UTC, merged